### ISSUE TITLE
데모에서 로마자가 뜨지 않습니다.

### ISSUE THREAD

**Issue by hisinsub** [crizin/korean-romanizer#1]
안녕하세요, 흥미로운 프로젝트네요. 근데 제 컴퓨터가 이상한건지,

http://unply.com/@/koreanRomanizer/

데모에서 로마자가 ????? 등으로 나옵니다.

**Comment by crizin** [comment]
알려주셔서 감사합니다. 수정 되었어요!

**Comment by hisinsub** [comment]
오 이제 잘 되네요. 감사합니다 ㅎㅎ
