### ISSUE TITLE
않다 --> anta

### ISSUE THREAD

**Issue by hisinsub** [crizin/korean-romanizer#2]
'않다'를 변환하면 'anda' 라고 나오는데, 'anta' 가 정확한 표기법인거 같습니다.
감사합니다.

참고: http://roman.cs.pusan.ac.kr/input_eng.aspx

**Comment by crizin** [comment]
말씀해주신 것 처럼 등 올바르지 않게 처리되는 여러 부분들을 수정했습니다.
알려주셔서 감사합니다!

**Comment by hisinsub** [comment]
업데이트해주셔서 감사합니다!
