### ISSUE TITLE
성이 '이'씨인 경우에 I 로만 표시되는 부분

### ISSUE THREAD

**Issue by jhyoodami** [crizin/korean-romanizer#3]
너무 잘 사용하고있습니다만, 
성이 '이'씨인 경우에는 I 로만 변환이 되는데, Lee 로 변환되도록 할 방법은 없을까요?
ex) 이평화 -> I Pyeonghwa

**Comment by crizin** [comment]
@jhyoodami 일반적으로 사용되는 성씨를 반영할 수 있도록 `KoreanCharacter.Type.NameTypical` 옵션을 추가한 2.0.1 버전을 릴리즈 했습니다
