### ISSUE TITLE
데모 웹 고쳐주셔서 감사합니다!

### ISSUE THREAD

**Issue by Guppy3063** [crizin/korean-romanizer#6]
아이폰 단축어로 http post 이용해서 사용하고 있는데
수정된 데모사이트가 ajax로 통신해서 데이터를 가져오기 힘들더라구요 ㅠㅠ..
혹시 query string 형식으로 바로 번역된 값을 구하게 수정은 어려우실까요?

https://unply.com/@/koreanRomanizer/?string=테스트&type=Name&consonantAssimilation=Regressive
접속시 test 값을 html 소스로 확인가능하게..

번거롭게 해드려서 죄송합니다.

**Comment by crizin** [comment]
말씀하신대로 동작할 수 있게 수정해봤습니다

**Comment by Guppy3063** [comment]
감사합니다!!
