### ISSUE TITLE
name type  '우' 는 'u' 가 아니라 'woo'로 표기 되어야 할 것 같습니다.

### ISSUE THREAD

**Issue by ericjoo98** [crizin/korean-romanizer#7]
인명 로마자 잘 쓰고 있습니다. 
원래 AHK나 C#만 할 줄 알았는데, 인명-로마자를 HTTP request 방식의 네이버클로바 무료변환 API 쓰고 있었습니다. 
이번에 네이버 개발자센터, 네이버 클로바 모두 인명 로마자 서비스 중단하게 되어 급하게 여러 사이트 찾아보았으나, 방법이 마땅치 않더라구요. 
crizin 님의 깃허브 웹예제를 써보고는 이거다 싶어 속성으로 JAVA 공부하고 라이브러리 적용해서 잘 빌드했습니다. 

그런데 인명type.default 나 typical 모두 '우' 는 'u' 가 아니라 'woo'로 표기 되어야 할 것 같습니다. 

수정 방법을 알려주시면 좋을 것 같습니다. 감사합니다.

**Comment by crizin** [comment]
인명의 경우 많이 알려진 성씨에 대해서는 예외 처리가 되어 있지만 이름 부분에는 특별한 처리를 하고 있지 않아서 일반적인 로마자 표기법을 따르고 있습니다.
인명을 제대로 표기하자면 규칙을 많이 추가해야되고 일반적으로 선호하는 표기는 있지만 뚜렷한 규칙이랄게 없어 프로그램으로 완벽히 처리하기는 좀 어렵지 않을까 싶네요.
그래서 수정은 어려울 것 같다는 말씀을 드려봅니다.
비용을 감수할 수 있다면 OpenAI API 같은걸 이용해서 변환을 시도해보는 것도 좋은 방법일 것 같습니다.
